### ISSUE TITLE
Does not appear the video when it is not in full screen mode.

### ISSUE THREAD

**Issue by reisraff** [veeplay/veeplay-web-standalone#1]
I am using the CDN 1.0.0 version of the script

![](https://gist.githubusercontent.com/reisraff/81524b4c6563159347e096808b64de67/raw/58843aceb7ac4f928cde75ba0c1d4fbbd73d0507/Screenshot%2520from%25202019-09-30%252014-31-56.png)

**Comment by ov1d1u** [comment]
Hi Rafael,

Can you provide a snippet which reproduce the issue? Also, what browser and version are you using?

Thanks.

**Comment by reisraff** [comment]
The snippet I'd used was the same you use in the example, the simple one. For me does not work as well youtube video.

My browser is: Google Chrome **Version 77.0.3865.90 (Official Build) (64-bit)**

**Comment by ov1d1u** [comment]
I was curious about the config JSON, so I can give it a try to see if I get the same results. I tried the basic snippet from the README and it works for me, with some minor modifications (a width and height for the player's div and [a working JSON configuration](https://github.com/veeplay/testing-samples/blob/master/Veeplay/JSON/08VastPreroll.json)). YouTube videos aren't yet supported in the JavaScript version of Veeplay.

**Comment by reisraff** [comment]
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Veeplay test</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- <style type="text/css">
        .vjs-tech {
            position: unset !important; /* hacking to be able see the video when it is not in fullscreen */
        }
    </style> -->
    <script src="https://cdn.veeplay.com/veeplay-web/1.0.0/mp.bundle.js"></script>
</head>
<body>

    <div class="container" style="padding-top: 150px">
        <!-- Content here -->
        <div id="player" style="border: 1px solid #000;min-height: 500px;"></div>
    </div>


    <script>
      (async () => {
        try {
          // instantiate main player object
          const player = new MediaPlayer('player');
          // instantiate a MediaBuilder object used for generating MediaUnits for configuring the main content and any abreaks
          const builder = new MediaBuilder(player);

          await builder.configureFromJSON({
            // Main content unit configuration
            "content": [
              {
                "url": "",
                "autoplay": true,
                "controls": {
                }
              }
            ]
          });

          // Retrieve the generated MediaUnits (the main class for encapsulating each piece of content that needs to be played)
          const units = await builder.mediaUnits();

          // Instruct the player to start playback
          player.playMediaUnits(units);
          // player.setMute();
        } catch (error) {
          console.error(error);
        }
      })();
    </script>
</body>
</html>
```

**Comment by ov1d1u** [comment]
I was able to reproduce the issue now. Seems that the player doesn't work with min-height, I will look into it to see why and I'll come back with an answer. Thanks!

**Comment by ov1d1u** [comment]
Hi @reisraff, can you give version 1.0.1 a shot? https://cdn.veeplay.com/veeplay-web/1.0.1/mp.bundle.js

**Comment by reisraff** [comment]
now it is working.
