### ISSUE TITLE
Setting autoplay to false continues trying to autoplay.

### ISSUE THREAD

**Issue by reisraff** [veeplay/veeplay-web-standalone#2]
Setting autoplay to false continues trying to autoplay.

**Comment by ov1d1u** [comment]
You mean that prerolls starts to play even if the main content has `"autoplay" = false`? Because I tried with https://raw.githubusercontent.com/veeplay/testing-samples/master/Veeplay/JSON/02MP4Progressive.json and it doesn't autoplay.

**Comment by reisraff** [comment]
lol, I just tested it now, and it works as expected. thanks, and sorry for it.

**Comment by ov1d1u** [comment]
Thanks! If you somehow manage to reproduce this please feel free to reopen the issue.
