### ISSUE TITLE
playsinline does not work on iphone

### ISSUE THREAD

**Issue by reisraff** [veeplay/veeplay-web-standalone#5]
*Device*: IPhone (iOS +11)
*Browoser*: Safari 11.0

The `playsinline` attribute added by veeplay does not work, it still is opening the native browser and going full screen.

**Comment by ov1d1u** [comment]
Hi Rafael,

If you're using the JS player in a `WKWebView` you need to set `allowsInlineMediaPlayback` to `true` in the configuration used to instantiate the webview or check the [Inline playback](https://i.imgur.com/BZOMiHh.png) checkbox in the property editor if you're using a Storyboard/XIB to instantiate the webview.

**Comment by reisraff** [comment]
I am not using webview. It is just a website that I open directly from safari.

**Comment by ov1d1u** [comment]
Can you provide an example which reproduce this issue? I tried in a simulator (I don't have an iDevice with iOS 11) and it's working [perfectly fine](https://i.imgur.com/VqwudEL.png).

**Comment by reisraff** [comment]
reference: https://www.reddit.com/r/ios/comments/ddsqss/safari_ios_13_fullscreen_api_permanently_on/
